version: '3'

services:
  web:
    image: jitsi/web:stable
    restart: always
    ports:
      - '8000:80'
    environment:
      - ENABLE_AUTH=0
      - ENABLE_GUESTS=1
      - ENABLE_LETSENCRYPT=0
      - PUBLIC_URL=https://selvandieumeme.github.io/live
      - TZ=America/Port-au-Prince
      - XMPP_SERVER=xmpp.meet.jitsi
    volumes:
      - web-config:/config

  prosody:
    image: jitsi/prosody:stable
    restart: always
    environment:
      - AUTH_TYPE=anonymous
    volumes:
      - prosody-config:/config

  jicofo:
    image: jitsi/jicofo:stable
    restart: always
    environment:
      - XMPP_DOMAIN=meet.jitsi
    volumes:
      - jicofo-config:/config

  jvb:
    image: jitsi/jvb:stable
    restart: always
    ports:
      - '10000:10000/udp'
    volumes:
      - jvb-config:/config

volumes:
  web-config:
  prosody-config:
  jicofo-config:
  jvb-config:
