version: '3'

services:
  web:
    image: jitsi/web:stable
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${CONFIG}/web:/config
    environment:
      - ENABLE_GUESTS=1
      - ENABLE_AUTH=0
      - ENABLE_LETSENCRYPT=0
      - PUBLIC_URL=https://localhost
      - TZ=America/Port-au-Prince
      - XMPP_SERVER=xmpp.meet.jitsi

  prosody:
    image: jitsi/prosody:stable
    restart: always
    volumes:
      - ${CONFIG}/prosody:/config
    environment:
      - AUTH_TYPE=anonymous

  jicofo:
    image: jitsi/jicofo:stable
    restart: always
    volumes:
      - ${CONFIG}/jicofo:/config
    environment:
      - XMPP_DOMAIN=meet.jitsi

  jvb:
    image: jitsi/jvb:stable
    restart: always
    ports:
      - '10000:10000/udp'
    volumes:
      - ${CONFIG}/jvb:/config
